/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_ProcessHandleImpl_Info */

#ifndef _Included_java_lang_ProcessHandleImpl_Info
#define _Included_java_lang_ProcessHandleImpl_Info
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_ProcessHandleImpl_Info
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_lang_ProcessHandleImpl_00024Info_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     java_lang_ProcessHandleImpl_Info
 * Method:    info0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_lang_ProcessHandleImpl_00024Info_info0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
